apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJtYWRodXBpeGllZSIsInBhc3N3b3JkIjoibWFkaHU1ODk3IiwiZW1haWwiOiJtYWRodW1pdGhyYW11dGh1a3VtYXJAZ21haWwuY29tIiwiYXV0aCI6ImJXRmthSFZ3YVhocFpXVTZiV0ZrYUhVMU9EazMifX19
kind: Secret
metadata:
  creationTimestamp: "2021-04-25T06:07:39Z"
  name: regcreden
  namespace: default
  resourceVersion: "4381"
  uid: f7795c67-c1df-489a-84df-7dc43ef574cb
type: kubernetes.io/dockerconfigjson
